# Generated by Django 6.0 on 2025-12-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: рисование, программирование, футбол', max_length=100, verbose_name='Название увлечения')),
                ('description', models.TextField(blank=True, help_text='Подробное описание увлечения', null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Увлечение',
                'verbose_name_plural': 'Увлечения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя друга')),
                ('email', models.EmailField(help_text='Уникальный email друга', max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('is_close_friend', models.BooleanField(default=False, verbose_name='Близкий друг')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hobbies', models.ManyToManyField(blank=True, related_name='friends', to='friends_api.hobby', verbose_name='Увлечения')),
            ],
            options={
                'verbose_name': 'Друг',
                'verbose_name_plural': 'Друзья',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название встречи')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание встречи')),
                ('location', models.CharField(max_length=200, verbose_name='Место встречи')),
                ('date', models.DateTimeField(verbose_name='Дата и время встречи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='meetings', to='friends_api.friend', verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
                'ordering': ['-date'],
            },
        ),
    ]
